//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/DroneInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DroneInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DroneInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DroneInputAction"",
    ""maps"": [
        {
            ""name"": ""Droner"",
            ""id"": ""d24298eb-2760-46e6-b85a-195436788c22"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""2b9ba455-7019-44c1-aebd-4b412dd5b902"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""80577e80-c9ba-4fb3-b6c0-10e762bbd478"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e1fb51cd-8feb-469e-be27-0312d47c7a4f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c304fad-16b4-4f6e-9865-0a7f52da9971"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Droner
        m_Droner = asset.FindActionMap("Droner", throwIfNotFound: true);
        m_Droner_Look = m_Droner.FindAction("Look", throwIfNotFound: true);
        m_Droner_Move = m_Droner.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Droner
    private readonly InputActionMap m_Droner;
    private List<IDronerActions> m_DronerActionsCallbackInterfaces = new List<IDronerActions>();
    private readonly InputAction m_Droner_Look;
    private readonly InputAction m_Droner_Move;
    public struct DronerActions
    {
        private @DroneInputAction m_Wrapper;
        public DronerActions(@DroneInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Droner_Look;
        public InputAction @Move => m_Wrapper.m_Droner_Move;
        public InputActionMap Get() { return m_Wrapper.m_Droner; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DronerActions set) { return set.Get(); }
        public void AddCallbacks(IDronerActions instance)
        {
            if (instance == null || m_Wrapper.m_DronerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DronerActionsCallbackInterfaces.Add(instance);
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IDronerActions instance)
        {
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IDronerActions instance)
        {
            if (m_Wrapper.m_DronerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDronerActions instance)
        {
            foreach (var item in m_Wrapper.m_DronerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DronerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DronerActions @Droner => new DronerActions(this);
    public interface IDronerActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
}
